# Generates src/panel_node_table.jl: the number of Gauss–Legendre nodes each
# fixed-rule elliptic panel needs, tabulated over atanh(b) and the length L of
# the integration interval in z (which grows like log(1/|y|) where the roots
# of the quartic pinch), for a set of target relative tolerances.
# Run from the repository root (takes several minutes):
#
#   julia -t auto --project=. calibration/panel_nodes.jl
#
# Each sample (b, y) records, per target, the smallest n whose relative error
# against a 200-bit reference stays below the target for every larger n, for
# both moment weights. A target below a sample's rounding floor (the median
# error of the 40- to 96-node rules) is replaced by three times that floor. Each bin keeps the maximum over its samples plus one node;
# bins without samples hold 0 and fall back to `panel_nodes`.
using FockExpansion, Printf, Statistics
const F = FockExpansion

const LEVELS = (1e-4, 1e-6, 1e-8, 1e-10, 1e-11, 1e-12, 1e-13, 1e-14)
const BETA = (-5.0, 5.0, 40)   # atanh(b) range and number of bins
const LZ = (0.0, 24.0, 24)     # L range and number of bins
const NMAX = 96

ref(b, y, c0, c2) = setprecision(BigFloat, 200) do
    Float64(first(F.panel_adaptive(big(b), big(y), big(c0), big(c2); rtol = big(1e-30))))
end

function needed(b, y)
    m = F.panelmap(b, y)
    need = fill(0, length(LEVELS))
    for (c0, c2) in ((1.0, 0.0), (0.0, 1.0))
        r = ref(b, y, c0, c2)
        err = [abs(F.panel_fixed(b, y, c0, c2, m, n)/r - 1) for n in 1:NMAX]
        floor = median(err[40:end])
        for (j, tol) in enumerate(LEVELS)
            t = max(tol, 3floor)
            n = NMAX
            while n > 1 && err[n - 1] <= t
                n -= 1
            end
            need[j] = max(need[j], n)
        end
    end
    m.zb - m.za, need
end

bin(v, (lo, hi, n)) = clamp(floor(Int, (v - lo)/(hi - lo)*n) + 1, 1, n)

# samples: β uniform (4 per bin), log10|y| uniform in [-12, 0]
βs = range(BETA[1], BETA[2], length = 4BETA[3] + 1)
λs = range(-12.0, 0.0, length = 121)
pts = [(tanh(β), -exp10(λ)) for β in βs for λ in λs]
results = Vector{Any}(undef, length(pts))
Threads.@threads for k in eachindex(pts)
    results[k] = needed(pts[k]...)
end

table = zeros(Int8, length(LEVELS), BETA[3], LZ[3])
for ((b, y), (L, need)) in zip(pts, results)
    L <= LZ[2] || continue
    i, j = bin(atanh(b), BETA), bin(L, LZ)
    table[:, i, j] .= max.(table[:, i, j], Int8.(min.(need .+ 1, NMAX)))
end

open(joinpath(@__DIR__, "..", "src", "panel_node_table.jl"), "w") do io
    println(io, "# Generated by calibration/panel_nodes.jl; do not edit.")
    println(io, "# PANEL_NODE_TABLE[k, i, j]: Gauss–Legendre nodes for relative tolerance")
    println(io, "# PANEL_NODE_LEVELS[k] in bin i of atanh(b) and bin j of the z-range L;")
    println(io, "# 0 marks a bin without samples.")
    println(io, "const PANEL_NODE_LEVELS=", LEVELS)
    println(io, "const PANEL_NODE_BETA=", BETA)
    println(io, "const PANEL_NODE_L=", LZ)
    println(io, "const PANEL_NODE_TABLE=reshape(Int8[")
    for v in Iterators.partition(vec(table), 32)
        println(io, "    ", join(v, ", "), ",")
    end
    println(io, "], ", size(table), ")")
end
@printf("wrote %d×%d×%d table from %d samples; filled bins %d of %d; node counts %d–%d\n",
        size(table)..., length(pts), count(!iszero, table[1, :, :]), BETA[3]*LZ[3],
        minimum(filter(!iszero, table)), maximum(table))
